{% set version = "0.6" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-radix
  version: {{ version|replace("-", "_") }}

source:
  fn: radix_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/radix_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/radix/radix_{{ version }}.tar.gz
  sha256: cbd2d8d9d796bd68d085deab5eb5342e3500d320042fd9b24ec4a0ae3cb02009

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-base64enc
    - r-digest
    - r-downloader
    - r-htmltools
    - r-jsonlite >=1.3
    - r-knitr >=1.15.6
    - r-lubridate
    - r-mime
    - r-png
    - r-progress
    - r-rmarkdown >=1.10
    - r-rprojroot
    - r-rstudioapi
    - r-stringr
    - r-whisker
    - r-xml2
    - r-yaml
  run:
    - r-base
    - r-base64enc
    - r-digest
    - r-downloader
    - r-htmltools
    - r-jsonlite >=1.3
    - r-knitr >=1.15.6
    - r-lubridate
    - r-mime
    - r-png
    - r-progress
    - r-rmarkdown >=1.10
    - r-rprojroot
    - r-rstudioapi
    - r-stringr
    - r-whisker
    - r-xml2
    - r-yaml

test:
  commands:
    - $R -e "library('radix')"           # [not win]
    - "\"%R%\" -e \"library('radix')\""  # [win]

about:
  home: https://github.com/rstudio/radix
  license: Apache 2.0
  summary: Scientific and technical article format for the web. 'Radix' articles  feature attractive,
    reader-friendly typography, flexible layout options for visualizations, and full
    support for footnotes and citations.
  license_family: APACHE

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
