{% set version = '0.6' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-radix
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/radix_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/radix/radix_{{ version }}.tar.gz
  sha256: cbd2d8d9d796bd68d085deab5eb5342e3500d320042fd9b24ec4a0ae3cb02009

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-base64enc
    - r-bookdown >=0.8
    - r-digest
    - r-downloader
    - r-htmltools
    - r-jsonlite >=1.3
    - r-knitr >=1.15.6
    - r-lubridate
    - r-mime
    - r-png
    - r-progress
    - r-rmarkdown >=1.10
    - r-rprojroot
    - r-rstudioapi
    - r-stringr
    - r-whisker
    - r-xfun >=0.2
    - r-xml2
    - r-yaml
  run:
    - r-base
    - r-base64enc
    - r-bookdown >=0.8
    - r-digest
    - r-downloader
    - r-htmltools
    - r-jsonlite >=1.3
    - r-knitr >=1.15.6
    - r-lubridate
    - r-mime
    - r-png
    - r-progress
    - r-rmarkdown >=1.10
    - r-rprojroot
    - r-rstudioapi
    - r-stringr
    - r-whisker
    - r-xfun >=0.2
    - r-xml2
    - r-yaml

test:
  commands:
    - $R -e "library('radix')"           # [not win]
    - "\"%R%\" -e \"library('radix')\""  # [win]

about:
  home: https://github.com/rstudio/radix
  license: Apache 2.0
  summary: Scientific and technical article format for the web. 'Radix' articles  feature attractive,
    reader-friendly typography, flexible layout options for visualizations, and full
    support for footnotes and citations.
  license_family: APACHE

extra:
  recipe-maintainers:
    - conda-forge/r

# Type: Package
# Package: radix
# Title: 'R Markdown' Format for Scientific and Technical Writing
# Version: 0.6
# Authors@R: c( person("JJ", "Allaire", role = c("aut", "cre"), email = "jj@rstudio.com"), person("Rich", "Iannone", role = c("aut")), person("Yihui", "Xie", role = c("aut")), person(family = "RStudio, Inc.", role = "cph"), person(family = "Google LLC", role = c("ctb", "cph"),  comment = "https://distill.pub/guide/"), person("Nick", "Williams", role = c("ctb", "cph"),  comment = "https://wicky.nillia.ms/headroom.js/"), person("Denis", "Demchenko", role = c("ctb", "cph"),  comment = "https://github.com/lancedikson/bowser"), person(family = "The Polymer Authors", role = c("ctb", "cph"),  comment = "https://www.webcomponents.org/polyfills/"), person("Gabor", "Csardi", role = c("ctb", "cph"), comment = "whoami") )
# Description: Scientific and technical article format for the web. 'Radix' articles  feature attractive, reader-friendly typography, flexible layout options for visualizations, and full support for footnotes and citations.
# License: Apache License 2.0
# URL: https://github.com/rstudio/radix
# BugReports: https://github.com/rstudio/radix/issues
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.0
# Imports: utils, stats, tools, rmarkdown (>= 1.10), bookdown (>= 0.8), xfun (>= 0.2), htmltools, jsonlite (>= 1.3), lubridate, png, mime, rstudioapi, rprojroot, xml2, base64enc, whisker, downloader, progress, stringr, knitr (>= 1.15.6), digest, yaml
# Suggests: htmlwidgets, r2d3, DiagrammeR, shiny, rsconnect, testthat
# Language: en-US
# NeedsCompilation: no
# Packaged: 2018-12-09 12:00:15 UTC; jjallaire
# Author: JJ Allaire [aut, cre], Rich Iannone [aut], Yihui Xie [aut], RStudio, Inc. [cph], Google LLC [ctb, cph] (https://distill.pub/guide/), Nick Williams [ctb, cph] (https://wicky.nillia.ms/headroom.js/), Denis Demchenko [ctb, cph] (https://github.com/lancedikson/bowser), The Polymer Authors [ctb, cph] (https://www.webcomponents.org/polyfills/), Gabor Csardi [ctb, cph] (whoami)
# Maintainer: JJ Allaire <jj@rstudio.com>
# Repository: CRAN
# Date/Publication: 2018-12-09 13:50:03 UTC
