travis:
  secure:
    BINSTAR_TOKEN: 3NYuVfrgeTCUseLLuo4owvgw8CTQwEr6MIRZk57wuqKEyEwCHF9fxgX5ZLfR8Yv4mFfr/NnhkmcBiCpmBPVuNqXsbgiYcGYDNb0BGnFkn5xbyG0HOmL7fKRsGqOX9Jmu56Ix0oFUJCZvHhEk1wslibMu4nOWvhkyTRNkdWr9zA+LNT1ig5c+6l2wFfHd0sXKFY/wH+V6G9tPgjRZ5u2/0KrVgd0MCPaxy9q5bKLKZT2dyQf1RAtreoPX5ScQp8yd+HFu4+nDxEY7fB+daArFlLJzGtKQyhjNH/5T0k7F+VnA+RT3rC5Tr3Gh1+A1at7WL5jFexmPSjxWQk4tWyzUS/+N4mNrGb4bt6OwT2Q/ubuiH9dy/QMd2BE5JY47cg2y8i6m7qnUknJer3skDg1jj7LWaxTV6DVGrgIGk0YhtXfQ3CzdqE9vx7nVRVIqVI2wR1a1Z1c0i+2iN4YQ7cxBwyKJPZWgewfU8nbxMooAAJHDP/krZrcwfTJ8kjx78VgvqCP9P8vRpaXmxiGi8Cotyca2dTTCXCe6LhO4quIQw8ck5zY5hVdoajeHQ/my27GArLwDlSNtm+v7PAdRE3wP8GkrYayT9aGFoprrbeKGtZsTxgEkMEemzKIMzp3KCeroSBY+B3DTU5BjRR5PPgSBNEjQwssRbucRzd8Yzi2S+J8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
